/* Generated by AN DISI Unibo */ 
package it.unibo.ctx_rasp
import it.unibo.kactor.QakContext
import it.unibo.kactor.sysUtil
import kotlinx.coroutines.runBlocking

fun main() = runBlocking {
	QakContext.createContexts(
	        "rasp", this, "transporttrolley.pl", "sysRules.pl","ctx_rasp"
	)
}

