version: '3'
services:
  wenv:
    image: thomasambrogini/virtualrobot:1.0
    ports:
      - 8090:8090 
      - 8091:8091/tcp
      - 8091:8091/udp
  robot:
    image: thomasambrogini/basicrobot22:2.0
    ports:
      - 8020:8020/tcp
      - 8020:8020/udp
    depends_on:
      - wenv

  wasteservice:
    image: thomasambrogini/wasteservice:2.0
    ports:
      #- 192.168.1.7:8049:8049/udp
        #- 192.168.1.7:8049:8049/tcp
      - 8049:8049/udp
      - 8049:8049/tcp
    depends_on:
      - robot
  transporttrolley:
    image: thomasambrogini/transporttrolley:1.0
    extra_hosts:
      - "rasp:192.168.1.11"
    ports:
      - 192.168.1.7:8051:8051/udp
      - 192.168.1.7:8051:8051/tcp
        #      - 8051:8051/udp
        #- 8051:8051/tcp
    depends_on:
      - wasteservice
  
  gui:
    image: thomasambrogini/gui:2.0
    extra_hosts:
      - "rasp:192.168.1.11"
    ports: 
      #      - 192.168.1.7:8085:8085/udp
      #      - 192.168.1.7:8085:8085/tcp
      - 8085:8085
        #      - 192.168.1.7:8085:8085
  
  truck_gui:
    image: thomasambrogini/truck_gui:1.0
    ports:
      - 8080:8080
    depends_on:
      - wasteservice
## -------------------------------------------------------------
## TODO See https://docs.docker.com/compose/startup-order/
## -------------------------------------------------------------
## docker-compose -f basicrobot22.yaml  up
## docker-compose run --service-ports wenv
## docker-compose run --service-ports vrobotclient  ATTIVA ANCHE wenv
