version: '3'
services:
  wenv:
    image: virtualrobot:1.0
    ports:
      - 8090:8090 
      - 8091:8091/tcp
      - 8091:8091/udp
  robot:
    image: basicrobot22:2.0
    ports:
      - 8020:8020/tcp
      - 8020:8020/udp
    depends_on:
      - wenv

  wasteservice:
    image: thomasambrogini/wasteservice:2.0
    ports:
      - 192.168.1.7:8049:8049/udp
      - 192.168.1.7:8049:8049/tcp
    depends_on:
      - robot
  transporttrolley:
    image: thomasambrogini/transporttrolley:1.0
    ports:
      - 192.168.1.7:8051:8051/udp
      - 192.168.1.7:8051:8051/tcp
    depends_on:
      - wasteservice
  
  gui:
    image: thomasambrogini/gui:2.0
    ports: 
      #      - 192.168.1.7:8085:8085/udp
      #      - 192.168.1.7:8085:8085/tcp
      - 8085:8085
        #      - 192.168.1.7:8085:8085


## -------------------------------------------------------------
## TODO See https://docs.docker.com/compose/startup-order/
## -------------------------------------------------------------
## docker-compose -f basicrobot22.yaml  up
## docker-compose run --service-ports wenv
## docker-compose run --service-ports vrobotclient  ATTIVA ANCHE wenv
