/* Generated by AN DISI Unibo */ 
package it.unibo.wasteservice

import it.unibo.kactor.*
import alice.tuprolog.*
import kotlinx.coroutines.CoroutineScope
import kotlinx.coroutines.delay
import kotlinx.coroutines.launch
import kotlinx.coroutines.runBlocking
	
class Wasteservice ( name: String, scope: CoroutineScope  ) : ActorBasicFsm( name, scope ){

	override fun getInitialState() : String{
		return "s0"
	}
	override fun getBody() : (ActorBasicFsm.() -> Unit){
		val interruptedStateTransitions = mutableListOf<Transition>()
		
				var CurrentPlasticWeight = 0L
				var CurrentGlassWeight   = 0L
				val MAXP				 = 200L
				val MAXG				 = 200L
		return { //this:ActionBasciFsm
				state("s0") { //this:State
					action { //it:State
						println("$name in ${currentState.stateName} | $currentMsg")
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
					 transition(edgeName="t00",targetState="handleTruck",cond=whenRequest("storeload"))
				}	 
				state("handleTruck") { //this:State
					action { //it:State
						println("$name in ${currentState.stateName} | $currentMsg")
						if( checkMsgContent( Term.createTerm("storeload(TYPE,LOAD)"), Term.createTerm("storeload(TYPE,LOAD)"), 
						                        currentMsg.msgContent()) ) { //set msgArgList
								
												val Type   = payloadArg(0)
												val Weight = payloadArg(1).toLong()	
								if(  Type.equals("glass") 
								 ){if(  CurrentGlassWeight + Weight <= MAXG  
								 ){answer("storeload", "loadaccepted", "loadaccepted(glass,$Weight)"   )  
								}
								else
								 {answer("storeload", "loadrejected", "loadrejected(glass,$Weight)"   )  
								 }
								}
								else
								 {if(  CurrentPlasticWeight + Weight <= MAXP  
								  ){answer("storeload", "loadaccepted", "loadaccepted(plastic,$Weight)"   )  
								 }
								 else
								  {answer("storeload", "loadrejected", "loadrejected(glass,$Weight)"   )  
								  }
								 }
						}
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
				}	 
			}
		}
}
