/* Generated by AN DISI Unibo */ 
package it.unibo.transporttrolley

import it.unibo.kactor.*
import alice.tuprolog.*
import kotlinx.coroutines.CoroutineScope
import kotlinx.coroutines.delay
import kotlinx.coroutines.launch
import kotlinx.coroutines.runBlocking
	
class Transporttrolley ( name: String, scope: CoroutineScope  ) : ActorBasicFsm( name, scope ){

	override fun getInitialState() : String{
		return "s0"
	}
	override fun getBody() : (ActorBasicFsm.() -> Unit){
		val interruptedStateTransitions = mutableListOf<Transition>()
		return { //this:ActionBasciFsm
				state("s0") { //this:State
					action { //it:State
						println("$name in ${currentState.stateName} | $currentMsg")
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
					 transition(edgeName="t00",targetState="move",cond=whenRequest("moveToDestination"))
					transition(edgeName="t01",targetState="rotate",cond=whenRequest("trolleyRotate"))
				}	 
				state("move") { //this:State
					action { //it:State
						println("$name in ${currentState.stateName} | $currentMsg")
						updateResourceRep( "work"  
						)
						if( checkMsgContent( Term.createTerm("info(X_DESTINATION,Y_DESTINATION)"), Term.createTerm("info(X_DESTINATION,Y_DESTINATION)"), 
						                        currentMsg.msgContent()) ) { //set msgArgList
								request("findPath", "findPath(${payloadArg(0)},${payloadArg(1)})" ,"transporttrolley_mover" )  
						}
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
					 transition(edgeName="t12",targetState="destinationReached",cond=whenReply("dopathdone"))
				}	 
				state("destinationReached") { //this:State
					action { //it:State
						println("$name in ${currentState.stateName} | $currentMsg")
						answer("moveToDestination", "destinationReached", "destinationReached(ok)"   )  
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
					 transition(edgeName="t23",targetState="handle_pickup",cond=whenRequest("pickup"))
					transition(edgeName="t24",targetState="handle_deposit",cond=whenRequest("deposit"))
					transition(edgeName="t25",targetState="move",cond=whenRequest("moveToDestination"))
					transition(edgeName="t26",targetState="rotate",cond=whenRequest("trolleyRotate"))
				}	 
				state("handle_pickup") { //this:State
					action { //it:State
						println("$name in ${currentState.stateName} | $currentMsg")
						delay(5000) 
						answer("pickup", "pickupDone", "pickupDone(true)"   )  
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
					 transition(edgeName="t37",targetState="move",cond=whenRequest("moveToDestination"))
				}	 
				state("handle_deposit") { //this:State
					action { //it:State
						println("$name in ${currentState.stateName} | $currentMsg")
						delay(5000) 
						answer("deposit", "depositDone", "depositDone(true)"   )  
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
					 transition(edgeName="t48",targetState="move",cond=whenRequest("moveToDestination"))
				}	 
				state("rotate") { //this:State
					action { //it:State
						println("$name in ${currentState.stateName} | $currentMsg")
						if( checkMsgContent( Term.createTerm("trolleyRotate(DIR)"), Term.createTerm("trolleyRotate(DIR)"), 
						                        currentMsg.msgContent()) ) { //set msgArgList
								
												val Dir = payloadArg(0)	
								request("trolleyRotate", "trolleyRotate($Dir)" ,"transporttrolley_mover" )  
						}
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
					 transition(edgeName="t59",targetState="rotateDone",cond=whenReply("rotateDone"))
				}	 
				state("rotateDone") { //this:State
					action { //it:State
						answer("trolleyRotate", "rotateDone", "rotateDone(OK)"   )  
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
					 transition( edgeName="goto",targetState="s0", cond=doswitch() )
				}	 
			}
		}
}
