/* Generated by AN DISI Unibo */ 
package it.unibo.transporttrolley

import it.unibo.kactor.*
import alice.tuprolog.*
import kotlinx.coroutines.CoroutineScope
import kotlinx.coroutines.delay
import kotlinx.coroutines.launch
import kotlinx.coroutines.runBlocking
	
class Transporttrolley ( name: String, scope: CoroutineScope  ) : ActorBasicFsm( name, scope ){

	override fun getInitialState() : String{
		return "s0"
	}
	override fun getBody() : (ActorBasicFsm.() -> Unit){
		
				var CurPosition = ""
				var Destination = ""
				var Container   = ""
				var Load        = 0L
		return { //this:ActionBasciFsm
				state("s0") { //this:State
					action { //it:State
						println("$name in ${currentState.stateName} | $currentMsg")
					}
					 transition(edgeName="t00",targetState="handleactivate",cond=whenRequest("activate"))
				}	 
				state("handleactivate") { //this:State
					action { //it:State
						println("$name in ${currentState.stateName} | $currentMsg")
						if( checkMsgContent( Term.createTerm("activate(TYPE,LOAD)"), Term.createTerm("activate(TYPE,LOAD)"), 
						                        currentMsg.msgContent()) ) { //set msgArgList
								
												Container = payloadArg(0)
												Load      = payloadArg(1).toLong()
						}
					}
					 transition( edgeName="goto",targetState="pathForIndoor", cond=doswitch() )
				}	 
				state("pathForIndoor") { //this:State
					action { //it:State
						println("$name in ${currentState.stateName} | $currentMsg")
						request("findPath", "findPath(indoor)" ,"pathfinder" )  
					}
					 transition(edgeName="t11",targetState="pickup",cond=whenReply("dopathdone"))
				}	 
				state("pickup") { //this:State
					action { //it:State
						println("$name in ${currentState.stateName} | $currentMsg")
						delay(1000) 
						println("Pickup done")
						answer("activate", "pickupDone", "pickupDone(ok)"   )  
					}
					 transition( edgeName="goto",targetState="pathForContainer", cond=doswitch() )
				}	 
				state("pathForContainer") { //this:State
					action { //it:State
						println("$name in ${currentState.stateName} | $currentMsg")
						request("findPath", "findPath($Container)" ,"pathfinder" )  
					}
					 transition(edgeName="t32",targetState="loaddeposit",cond=whenReply("dopathdone"))
				}	 
				state("loaddeposit") { //this:State
					action { //it:State
						println("$name in ${currentState.stateName} | $currentMsg")
						delay(1000) 
						println("Deposit Done")
						emit("loaddeposit", "loaddeposit($Container,$Load)" ) 
						stateTimer = TimerActor("timer_loaddeposit", 
							scope, context!!, "local_tout_transporttrolley_loaddeposit", 5.toLong() )
					}
					 transition(edgeName="t43",targetState="findPathHome",cond=whenTimeout("local_tout_transporttrolley_loaddeposit"))   
					transition(edgeName="t44",targetState="handleactivate",cond=whenRequest("activate"))
				}	 
				state("findPathHome") { //this:State
					action { //it:State
						println("$name in ${currentState.stateName} | $currentMsg")
						request("findPath", "findPath(home)" ,"pathfinder" )  
					}
					 transition(edgeName="t55",targetState="s0",cond=whenReply("dopathdone"))
				}	 
			}
		}
}
