/* Generated by AN DISI Unibo */ 
package it.unibo.transporttrolley_mover

import it.unibo.kactor.*
import alice.tuprolog.*
import kotlinx.coroutines.CoroutineScope
import kotlinx.coroutines.delay
import kotlinx.coroutines.launch
import kotlinx.coroutines.runBlocking
	
class Transporttrolley_mover ( name: String, scope: CoroutineScope  ) : ActorBasicFsm( name, scope ){

	override fun getInitialState() : String{
		return "s0"
	}
	override fun getBody() : (ActorBasicFsm.() -> Unit){
		val interruptedStateTransitions = mutableListOf<Transition>()
		
				var RemainingPath = ""
		return { //this:ActionBasciFsm
				state("s0") { //this:State
					action { //it:State
						println("$name in ${currentState.stateName} | $currentMsg")
						 
									unibo.kotlin.planner22Util.initAI();
									unibo.kotlin.planner22Util.loadRoomMap("mapRoomEmpty");
									unibo.kotlin.planner22Util.showMap();
									unibo.kotlin.planner22Util.showCurrentRobotState();
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
					 transition( edgeName="goto",targetState="idle", cond=doswitch() )
				}	 
				state("idle") { //this:State
					action { //it:State
						println("$name in ${currentState.stateName} | $currentMsg")
						updateResourceRep( "trolleyState(idle)"  
						)
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
					 transition(edgeName="t010",targetState="stopped",cond=whenDispatch("stop"))
					transition(edgeName="t011",targetState="findThePath",cond=whenRequest("findPath"))
					transition(edgeName="t012",targetState="rotate",cond=whenRequest("trolleyRotate"))
				}	 
				state("findThePath") { //this:State
					action { //it:State
						updateResourceRep( "trolleyState(work)"  
						)
						
									var MovesToDo = ""	
						println("$name in ${currentState.stateName} | $currentMsg")
						if( checkMsgContent( Term.createTerm("findPath(X_DESTINATION,Y_DESTINATION)"), Term.createTerm("findPath(X_DESTINATION,Y_DESTINATION)"), 
						                        currentMsg.msgContent()) ) { //set msgArgList
								
												val X_Destination = payloadArg(0)
												val Y_Destination = payloadArg(1)
												unibo.kotlin.planner22Util.planForGoal( X_Destination, Y_Destination )
												MovesToDo = unibo.kotlin.planner22Util.getActions().joinToString("")
												pathut.setPath(MovesToDo)
												pathut.updateMap()
						}
						println(MovesToDo)
						request("dopath", "dopath($MovesToDo)" ,"pathexec" )  
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
					 transition(edgeName="t113",targetState="alarm",cond=whenDispatch("stop"))
					transition(edgeName="t114",targetState="pathDone",cond=whenReply("dopathdone"))
					transition(edgeName="t115",targetState="handle_resume",cond=whenReply("dopathfail"))
				}	 
				state("pathDone") { //this:State
					action { //it:State
						println("$name in ${currentState.stateName} | $currentMsg")
						answer("findPath", "dopathdone", "dopathdone(ok)"   )  
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
					 transition( edgeName="goto",targetState="idle", cond=doswitch() )
				}	 
				state("alarm") { //this:State
					action { //it:State
						println("$name in ${currentState.stateName} | $currentMsg")
						emit("alarm", "alarm(STOP)" ) 
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
				 	 		stateTimer = TimerActor("timer_alarm", 
				 	 					  scope, context!!, "local_tout_transporttrolley_mover_alarm", 1000.toLong() )
					}	 	 
					 transition(edgeName="t616",targetState="stopped",cond=whenTimeout("local_tout_transporttrolley_mover_alarm"))   
					transition(edgeName="t617",targetState="stopped",cond=whenReply("dopathdone"))
					transition(edgeName="t618",targetState="savepath",cond=whenReply("dopathfail"))
				}	 
				state("savepath") { //this:State
					action { //it:State
						println("$name in ${currentState.stateName} | $currentMsg")
						if( checkMsgContent( Term.createTerm("dopathfail(ARG)"), Term.createTerm("dopathfail(PATH)"), 
						                        currentMsg.msgContent()) ) { //set msgArgList
								
												RemainingPath = payloadArg(0)
						}
						println("TROLLEY | SAVE PATH: $RemainingPath")
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
					 transition( edgeName="goto",targetState="stopped", cond=doswitch() )
				}	 
				state("stopped") { //this:State
					action { //it:State
						println("$name in ${currentState.stateName} | $currentMsg")
						println("TROLLEY | STOPPED")
						updateResourceRep( "trolleyState(stopped)"  
						)
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
					 transition(edgeName="t719",targetState="handle_resume",cond=whenDispatch("resume"))
				}	 
				state("handle_resume") { //this:State
					action { //it:State
						println("$name in ${currentState.stateName} | $currentMsg")
						updateResourceRep( "trolleyState(work)"  
						)
						if( checkMsgContent( Term.createTerm("resume(_)"), Term.createTerm("resume(STATE)"), 
						                        currentMsg.msgContent()) ) { //set msgArgList
								request("dopath", "dopath($RemainingPath)" ,"pathexec" )  
								 RemainingPath = ""  
						}
						if( checkMsgContent( Term.createTerm("dopathfail(ARG)"), Term.createTerm("dopathfail(ARG)"), 
						                        currentMsg.msgContent()) ) { //set msgArgList
								
												var RemainingPath = payloadArg(0)
								if(  RemainingPath.length == 1 || RemainingPath.length == 0 
								 ){ RemainingPath = ""  
								request("dopath", "dopath($RemainingPath)" ,"pathexec" )  
								}
								else
								 {request("dopath", "dopath($RemainingPath)" ,"pathexec" )  
								 }
						}
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
				 	 		stateTimer = TimerActor("timer_handle_resume", 
				 	 					  scope, context!!, "local_tout_transporttrolley_mover_handle_resume", 5000.toLong() )
					}	 	 
					 transition(edgeName="t220",targetState="idle",cond=whenTimeout("local_tout_transporttrolley_mover_handle_resume"))   
					transition(edgeName="t221",targetState="stopped",cond=whenDispatch("stop"))
					transition(edgeName="t222",targetState="pathDone",cond=whenReply("dopathdone"))
					transition(edgeName="t223",targetState="handle_resume",cond=whenReply("dopathfail"))
				}	 
				state("rotate") { //this:State
					action { //it:State
						println("$name in ${currentState.stateName} | $currentMsg")
						if( checkMsgContent( Term.createTerm("trolleyRotate(DIR)"), Term.createTerm("trolleyRotate(DIR)"), 
						                        currentMsg.msgContent()) ) { //set msgArgList
								
												val Path = pathut.getRotation(payloadArg(0))
												pathut.setPath(Path)
												pathut.updateMap()
								request("dopath", "dopath($Path)" ,"pathexec" )  
						}
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
					 transition(edgeName="t524",targetState="rotateDone",cond=whenReply("dopathdone"))
					transition(edgeName="t525",targetState="handle_resume",cond=whenReply("dopathfail"))
				}	 
				state("rotateDone") { //this:State
					action { //it:State
						answer("trolleyRotate", "rotateDone", "rotateDone(OK)"   )  
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
					 transition( edgeName="goto",targetState="idle", cond=doswitch() )
				}	 
			}
		}
}
