/* Generated by AN DISI Unibo */ 
package it.unibo.sonarqak22

import it.unibo.kactor.*
import alice.tuprolog.*
import kotlinx.coroutines.CoroutineScope
import kotlinx.coroutines.delay
import kotlinx.coroutines.launch
import kotlinx.coroutines.runBlocking
	
class Sonarqak22 ( name: String, scope: CoroutineScope  ) : ActorBasicFsm( name, scope ){

	override fun getInitialState() : String{
		return "s0"
	}
	@kotlinx.coroutines.ObsoleteCoroutinesApi
	@kotlinx.coroutines.ExperimentalCoroutinesApi			
	override fun getBody() : (ActorBasicFsm.() -> Unit){
		 
			   val simulate       = true
			   val sonarActorName = "sonarqak22"
		return { //this:ActionBasciFsm
				state("s0") { //this:State
					action { //it:State
						sonarConfig.configureTheSonar( simulate, sonarActorName  )
					}
					 transition( edgeName="goto",targetState="idle", cond=doswitch() )
				}	 
				state("idle") { //this:State
					action { //it:State
					}
					 transition(edgeName="t049",targetState="activateTheSonar",cond=whenDispatch("sonaractivate"))
					transition(edgeName="t050",targetState="deactivateTheSonar",cond=whenDispatch("sonardeactivate"))
				}	 
				state("activateTheSonar") { //this:State
					action { //it:State
						println("$name in ${currentState.stateName} | $currentMsg")
						if(   `it.unibo`.radarSystem22.domain.utils.DomainSystemConfig.simulation  
						 ){forward("sonaractivate", "info(ok)" ,"sonarsimulator" ) 
						}
						else
						 {forward("sonaractivate", "info(ok)" ,"sonardatasource" ) 
						 }
					}
					 transition(edgeName="t051",targetState="handleSonarData",cond=whenEvent("sonar"))
					transition(edgeName="t052",targetState="deactivateTheSonar",cond=whenDispatch("sonardeactivate"))
				}	 
				state("deactivateTheSonar") { //this:State
					action { //it:State
						println("$name in ${currentState.stateName} | $currentMsg")
					}
					 transition( edgeName="goto",targetState="end", cond=doswitch() )
				}	 
				state("handleSonarData") { //this:State
					action { //it:State
						println("$name in ${currentState.stateName} | $currentMsg")
						if( checkMsgContent( Term.createTerm("distance(V)"), Term.createTerm("distance(D)"), 
						                        currentMsg.msgContent()) ) { //set msgArgList
								 val D = payloadArg(0)  
								println("%%%%%%%%%%%%%%%%%%%%%%%%%%% emit %%%%%%%%%%%%%%% ${D}")
								emit("sonardata", "distance($D)" ) 
								updateResourceRep( "$D"  
								)
						}
					}
					 transition(edgeName="t053",targetState="handleSonarData",cond=whenEvent("sonar"))
					transition(edgeName="t054",targetState="deactivateTheSonar",cond=whenDispatch("sonardeactivate"))
				}	 
				state("end") { //this:State
					action { //it:State
						println("sonarqak22 Deactivated")
					}
					 transition( edgeName="goto",targetState="idle", cond=doswitch() )
				}	 
			}
		}
}
