/* Generated by AN DISI Unibo */ 
package it.unibo.ctxwasteservice_prototype
import it.unibo.kactor.QakContext
import it.unibo.kactor.sysUtil
import kotlinx.coroutines.runBlocking

fun main() = runBlocking {
	QakContext.createContexts(
	        "localhost", this, "wasteservice.pl", "sysRules.pl","ctxwasteservice_prototype"
	)
}

