version: '3'
services:
  wenv:
    image: virtualrobot:1.0
    ports:
      - 8090:8090 
      - 8091:8091/tcp
      - 8091:8091/udp
  robot:
    image: basicrobot22:2.0
    ports:
      - 8020:8020/tcp
      - 8020:8020/udp
    depends_on:
      - wenv

  wasteservice:
    image: wasteservice:1.0
    ports:
      - 8049:8049/udp
      - 8049:8049/tcp
    depends_on:
      - robot
   
   transporttrolley:
    image: thomasambrogini/transporttrolley:2.0
      - 8020:8020/udp
      - 8020:8020/tcp
    depends_on:
      - wasteservice
       


