version: '3'
services:
  rasp:
    image: thomasambrogini/rasp:1.5
    extra_hosts:
      - "transporttrolley:192.168.1.7"
      - "wasteservice:192.168.1.7"
    ports:
      - 8056:8056/udp
      - 8056:8056/tcp
